### ISSUE TITLE
How to select a particular image

### ISSUE THREAD

**Issue by ayodelesalimon** [esysberlin/esys-flutter-share#11]
I have a Container holding my images.
`Container(
          child: Stack(
            children: <Widget>[
              Align(
                alignment: Alignment.center,
                child: Hero(
                  tag: widget.imageList,
                  child: Img(
                    ayo: widget.imageList,
                  ),
                ),`

How can be able to share the particluar image the container is holding at the moment. Because there are various images in my image folder.

**Comment by kelegorm** [comment]
If you get widget with image you can render it into bytes. Wrap widget into RepaintBoundary (with key). Then find it and render:
```
final RenderRepaintBoundary boundary = _globalKey.currentContext.findRenderObject();
final image = await boundary.toImage();
final byteData = await image.toByteData(format: ImageByteFormat.png);
final pngBytes = byteData.buffer.asUint8List();
```
