### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by d-wolf** [esysberlin/esys-flutter-share#13]
[Migrate](https://developer.android.com/jetpack/androidx/migrate) the plugin to AndroidX.

**Comment by dukaric1991** [comment]
In 
esys_flutter_share-0.0.8\android\src\main\java\de\esys\esysfluttershare\EsysFlutterShareFileProvider.java
and
esys_flutter_share-0.0.8\android\src\main\java\de\esys\esysfluttershare\EsysFlutterSharePlugin.java

i changed from android.support.v4.content.FileProvider --> androidx.core.content.FileProvider
and now it works :)

**Comment by d-wolf** [comment]
0.0.9 supports androidX now.
