### ISSUE TITLE
Please specify SWIFT_VERSION

### ISSUE THREAD

**Issue by sbeitzel** [esysberlin/esys-flutter-share#15]
I'm trying to use this plugin in a project where I share an image to email, but I can't do it just yet. When I enable the plugin, the project won't build for iOS. I get this output:

    - `esys_flutter_share` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by gustavobrian** [comment]
**hi, equals**
esys_flutter_share` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
**Thanks, thanks for your works...
wait for solution...**

**Comment by gustavobrian** [comment]
please... resolve this problems!!!
Thanks...
I love you!!!!

**Comment by gustavobrian** [comment]
hi... resolve  link:
https://github.com/fluttercommunity/flutter_contacts/issues/19

**Comment by d-wolf** [comment]
Hi @gustavobrian. Unfortunately i have no idea what to fix and where i should fix that. Could you please provide a pull request?

**Comment by OpticNectar** [comment]
It seems you have to create your project with `flutter create -i swift my_app` for plugins that use swift work properly. It may be a good idea to add a note for this like this plugin did:

https://pub.dartlang.org/packages/flutter_inappbrowser

**Comment by sbeitzel** [comment]
Okay, so it seems that the problem lies not in this plugin but in the flutter project which depends on the plugin. This issue should therefore become a documentation issue:

1. This plugin's documentation should indicate that the plugin uses Swift and if one is using it in a project which was initialized to use Objective C (the flutter default) then the project must be edited.
1. Flutter's documentation for plugin writers ought to be updated to describe this situation so that the solution can be easier to find (this is not the responsibility of this plugin).
