### ISSUE TITLE
EsysFlutterSharePlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by juliengit2** [esysberlin/esys-flutter-share#18]
We get this warning when we run the app:

> EsysFlutterSharePlugin.java uses unchecked or unsafe operations.

I think this comes up in Java 5 and later if you're using collections without type specifiers (e.g., Arraylist() instead of ArrayList<String>()). It means that the compiler can't check that you're using the collection in a type-safe way, using generics.

To get rid of the warning, just be specific about what type of objects you're storing in the collection. So, instead of

List myList = new ArrayList();

use

List<String> myList = new ArrayList<String>();

or in java7:  List<String> myList = new ArrayList<>();
(remark : you still need angle brackets)

**Comment by d-wolf** [comment]
It's because of the Hashmaps. Warnings suppressed in 1.0.2
