### ISSUE TITLE
Cannot share images from some particular folders

### ISSUE THREAD

**Issue by kaxp** [esysberlin/esys-flutter-share#19]
Hello everyone, I'm trying to share images in my app, but with the esys-flutter-share version 1.0.1 I cannot share images from some particular folders such as from Whatsapp folder, previously with version 0.0.7 I was able to share all the photos but now with this latest version I cannot share all the photos. As with photos from whatsapp my code doesn't go to the 2nd line of this code, it just exits from the 1st line 

    final ByteData bytes = await rootBundle.load(widget.image.path);

    await Share.file('Sharing the best Captions & Hashtags directly from the App!', 'esys.png', bytes.buffer.asUint8List(), 'image/png');

I'm able to get the path in both cases but in the 2nd case, it doesn't go to the second line.
Please help me solve this problem as the app is live and needed to update the app asap. TIA

**Comment by lesnitsky** [comment]
@kaxp you should use `rootBundle` only to load your own assets packaged with app. To read other files on device use `getExternalStorageDirectory` from `path_provider` package
You will probably also need some permissions plugin to get storage permission
