### ISSUE TITLE
Add support for other filetypes

### ISSUE THREAD

**Issue by giovapanasiti** [esysberlin/esys-flutter-share#2]
I'm using shareImage method to share a pdf and it's working smoothly on android. but this is the error i get when i try it on ios `warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.` and it makes my app crash

**Comment by d-wolf** [comment]
Hi @giovapanasiti, at the moment the plugin just supports .jpg & .png image files. We will add support for other file types in the future.

**Comment by giovapanasiti** [comment]
In case other people are interested I am in supporting PDFs. Sharing a PDF works fine in android.

**Comment by aryan29** [comment]
Do you have any idea how I can share an apk this plugin is not working
