### ISSUE TITLE
Cannot share title?

### ISSUE THREAD

**Issue by adrianvintu** [esysberlin/esys-flutter-share#28]
I am using 
await Share.file('esys image', 'esys.png', bytes.buffer.asUint8List(), 'image/png', text: 'My optional text.');

like in your example.

On Android, the TITLE from the method does not appear as the Subject in GMAIL or YAHOO app.

I wish that the title of the method would be shared as TITLE on the email apps, both on Android and on iOS.

I know it's possible on Android using java native, not sure about iOS.

**Comment by d-wolf** [comment]
The title parameter is not made for email header. It's the title of the Android share dialog. To track the E-Mail feature request, see https://github.com/esysberlin/esys-flutter-share/issues/17.
