### ISSUE TITLE
iOS share to "Save File" crashes app

### ISSUE THREAD

**Issue by johnnygizmo** [esysberlin/esys-flutter-share#38]
**Describe the bug**
When I try the “save file” option on the iOS sharing intent. I can share to anything else (twitter, iMessage, dropbox, etc), and it works as expected, but if I choose “Save file”, it crashes my flutter app, even with the try/catch.

**To Reproduce**
```
Future<Uint8List> getCurrentImage() async {
    RenderRepaintBoundary rpb =
        boardGlobalKey.currentContext.findRenderObject();
    ui.Image img = await rpb.toImage();
    ByteData byteData = await img.toByteData(format: ui.ImageByteFormat.png);
    return byteData.buffer.asUint8List();
  }

  Future<void> shareImage() async {
    try {
      await Share.file(
        'Pedalboard Image',
        'pedalboard.png',
        await getCurrentImage(),
        'image/png',
      );
    } catch (e) {
      debugPrint(e.toString());
    }
  }
```
on iOS, then choose "Save File"

**Expected behavior**
file is saved to device

**Smartphone (please complete the following information):**
 - Device: iPhone 6s, Xr, Simulator (XR), iPad 2
 - OS: various

**Comment by johnnygizmo** [comment]
This is not an issue with esys-flutter-share. Rather you need to set a value for NSPhotoLibraryUsageDescription in your plist file. 

`<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Allow the user to save sample pics to their images.</string>`

[Apple Docs](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW17)

**Comment by vemarav** [comment]
iOS 10 and older
```
<key>NSPhotoLibraryUsageDescription</key>
<string/>
```

iOS 11 and later
```
<key>NSPhotoLibraryAddUsageDescription</key>
<string/>
```

![Screenshot 2020-08-06 at 12 56 20 PM](https://user-images.githubusercontent.com/17309962/89503684-84dfdb80-d7e4-11ea-8418-beafa02a8c51.png)

**Comment by Ludonope** [comment]
@johnnygizmo it could be interesting to add that element to the main documentation, since it might not be obvious to every flutter developper ;)

**Comment by momentocapture** [comment]
@johnnygizmo Did you ever find a solution to this bug? I am seeing the same iOS behavior on my photo sharing build.
