### ISSUE TITLE
Latest Instagram Version Sharing Image to Instagram Feed Doesn't Work

### ISSUE THREAD

**Issue by erdoganabaci** [esysberlin/esys-flutter-share#57]
**Describe the bug**
In the **latest version** of instagram (133.0.0.32.120 ) it only creates problems when feeding pictures
Instagram story and video feature works well but **just sharing image to instagram feed doesn't work.**
However every feature works well **in the previous version of Instagram (132.0.0.26.134 )**

**Expected behavior**
Image file is expected to shared to feed via instagram latest version

**Screenshots**
![Screenshot_1584892297](https://user-images.githubusercontent.com/43154455/77253872-7e562a80-6c6e-11ea-92bf-bbd1f5f11654.png)

![Screenshot_1584892335](https://user-images.githubusercontent.com/43154455/77253885-962dae80-6c6e-11ea-81d4-6a6b1dc1ea6e.png)

**Smartphone (please complete the following information):**
 - Device: Android Api 28
 - Instagram Version [133.0.0.32.120]

**Additional context**
Please help how to solve instagram to feed image in the instagram latest version(133.0.0.32.120).

**Comment by poshpawstudio** [comment]
I have the exactly same issue. Video shares fine, but image fails.

**Comment by ysnklcky** [comment]
I have same issue, instagram feed and messenger story.

It seems an android problem because this occurs after android 10 update.

**Comment by mauriblint** [comment]
Hello guys, I'm having the same issue here, is not working for Instagram Feed, but Stories

**Comment by ysnklcky** [comment]
Please guys, if you find solution, update here..

**Comment by mauriblint** [comment]
The is a ticket on Facebook Bugs, please leave a message there if you are having the same problem: https://developers.facebook.com/support/bugs/1326888287510350/

**Comment by mauriblint** [comment]
Workaround solution to fix temporary this IG bug (I think is a bug from the Instagram app)
https://stackoverflow.com/questions/60776730/instagram-android-share-intent-unable-to-load-image
