### ISSUE TITLE
Build Error D8: Program type already present: android.support.v4.app.FrameMetricsAggregator

### ISSUE THREAD

**Issue by jmall** [esysberlin/esys-flutter-share#6]
When I try to insert this plugin, I am getting this error:

> Note: /Users/mac/flutter/.pub-cache/hosted/pub.dartlang.org/esys_flutter_share-0.0.6/android/src/main/java/de/esys/esysfluttershare/EsysFlutterSharePlugin.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> D8: Program type already present: android.support.v4.app.FrameMetricsAggregator
> 
> FAILURE: Build failed with an exception.

**Comment by d-wolf** [comment]
````
Note: /Users/mac/flutter/.pub-cache/hosted/pub.dartlang.org/esys_flutter_share-0.0.6/android/src/main/java/de/esys/esysfluttershare/EsysFlutterSharePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
````
This Warning can be ignored. The problem is this one: 
````
D8: Program type already present: android.support.v4.app.FrameMetricsAggregator
FAILURE: Build failed with an exception.
````

If i create a new Project using the Plugin, everything works like expected. Do you use other Plugins in combination?

**Comment by jmall** [comment]
I tried again and it does not work.
It may be a conflict with other Plugins. Here are my Plugins:
 

> cupertino_icons: ^0.1.2
>   flutter_staggered_grid_view: "^0.2.5"
>   http: ^0.12.0
>   zoomable_image: ^1.2.1+1
>   image_downloader: ^0.9.1
>   material_search: ^0.2.8
>   url_launcher: ^4.0.3
>   flutter_simple_video_player: ^0.0.8
>   esys_flutter_share: ^0.0.6
>
flutter doctor gives me just a warning:

> [!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/mac/Library/Android/sdk
>     • Android NDK at /Users/mac/Library/Android/sdk/ndk-bundle
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

**Comment by d-wolf** [comment]
We've updated the plugin to 0.0.7 for sdk version 28 support. I hope this will fix the problem.

**Comment by jmall** [comment]
Yes! It works perfect, Thank you
I already uploaded it to Google Play,
Thanks
