### ISSUE TITLE
esys_flutter_share text to whatsapp failed

### ISSUE THREAD

**Issue by johnmelodyme** [esysberlin/esys-flutter-share#81]
esys_flutter_share text to whatsapp failed...

I cant Share a text to Whatsapp which previously can .

**Comment by savanbthakkar** [comment]
This code used to work a month ago in Android and iOS both. But it doesn't work in iOS anymore. Problem is only with WhatsApp. Sharing with other apps is fine. If I remove text parameter, it works just fine.

await Share.file(
      'My APP', 'MyAppImage.png', pngBytes, 'image/png', text:'Download my App'
    );

**Comment by johnmelodyme** [comment]
"The problem is with whatsapp, understood"

**Comment by ssjuma** [comment]
it also happens to me. on ios whatsapp, i dont get the image i add text into share. any solution for this
